services:
  web:
    build: .
    command:  bash -c "gunicorn resume_checker.wsgi:application --bind 0.0.0.0:8001 --reload --timeout 120 --workers 3"
    restart: always
    volumes:
      - .:/app
      - static_files:/app/resume_checker/staticfiles/
      - media_files:/app/resume_checker/media/
    env_file:
      - .env  # This ensures the .env file is loaded
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
  static_files:
  media_files:
