services:
  web:
    build: .
    command: gunicorn resume_checker.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
      - static_files:/app/resume_checker/staticfiles/
      - media_files:/app/resume_checker/media/
    env_file:
      - .env  # This ensures the .env file is loaded
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_files:
  media_files:
