services:
  be:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 resume_checker.wsgi:application
    volumes:
      - .:/app
    env_file:
      - .env  # This will ensure the .env file is loaded
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - be

volumes:
  postgres_data:
