services:
  web:
    build: .
    command: bash -c "gunicorn resume_checker.wsgi:application --bind 0.0.0.0:8001 --reload --timeout 120 --workers 3"
    restart: always
    volumes:
      - .:/app
      - static_files:/app/resume_checker/staticfiles
      - media_files:/app/resume_checker/media
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      - static_files:/app/resume_checker/staticfiles
      - media_files:/app/resume_checker/media
    depends_on:
      - web
  
  certbot:
    image: certbot/certbot
    volumes: 
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw

volumes:
  postgres_data:
  static_files:
  media_files:
