services:
  web:
    build: .
    command: gunicorn resume_checker.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
      - static_files:/app/resume_checker/staticfiles/
      - media_files:/app/resume_checker/media/
    env_file:
      - .env  # This ensures the .env file is loaded
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/app/resume_checker/staticfiles/
      - media_files:/app/resume_checker/media/
      - /var/certbot/conf:/etc/letsencrypt  # SSL certificates
      - /var/certbot/www:/var/www/certbot  # Certbot webroot
    depends_on:
      - web

volumes:
  postgres_data:
  static_files:
  media_files:
